[package]
name = "fluent-ansi"
description = "A fluent interface for ANSI terminal colors and styles in Rust."
version = "0.4.0"
license = "MIT"
repository = "https://github.com/erdavila/fluent-ansi"
keywords = ["ansi", "terminal", "colors", "styles"]
categories = ["command-line-interface", "no-std", "no-std::no-alloc"]
edition = "2024"
exclude = ["docs/**", "build.sh", "GEMINI.md"]

[dependencies]
enum-iterator = "2.3.0"
replace_with = { version = "0.1.8", default-features = false }

[dev-dependencies]
terminal_size = "0.4.3"
